### PR TITLE
Added README.md as per issue #1

### PR DESCRIPTION
**Pull request by d-stahl-ericsson**

### CODE REVIEW

**Comment by p-backman-ericsson** [comment]
I think the acronyms look good. The ET need to be discussed further. In CI we have had a quite relaxed approach to environments so far but in this context it is important. Reading up on ED it is defined as a definition/blueprint of an environment (even though you can point to a host) but in this context we need an ED that is an executing environment. Perhaps we can reuse the ED using a host or we need something else...

**Comment by d-stahl-ericsson** [comment]
I think ED as it is described is applicable to what we're trying to do with this extension, don't you? It doesn't have to be a host, but it can be. It pretty much depends on what level of granularity you're comfortable with. But yes, I would see pointing to a VM as a host as a typical use case.

**Comment by erobged** [comment]
uc

@d-stahl-ericsson @l-ohlen-ericsson @rogpers-ericsson @ebopalm 

Bo and I have been looking at the EnvironmentDefinedEvent from the Continuous Ops  perspective . (rather than from the CI perspective).
Attached is a diagram of our view.
Basically we think a new event EiffelAssetCreatedEvent is needed if we are to use the EnvironmentDefinedEvent.
This EiffelAssetCreatedEvent should meet the needs of Continuous Operations in terms of capturing what we would like in a deployment scenario.

Shall I arrange a short meeting to discuss the diagram ?

**Comment by rogpers-ericsson** [comment]
A discussion as proposed above would probably be a good thing.

Johan Lundberg should be called to this as he, together with BICP, is working actively in this area.

**Comment by l-ohlen-ericsson** [comment]
Some thoughts:
[Eiffel_Env.pptx](https://github.com/Ericsson/eiffel-operations-extension/files/796366/Eiffel_Env.pptx)

**Comment by erobged** [comment]
this is now invalid in the current context of the CO Events.

**Pull request closed without merging**
